{% set name = "pyrundeck" %}
{% set version = "0.9.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrundeck-{{ version }}.tar.gz
  sha256: 394e9c88f2affdd7dc71c4632e71b259952ef32831f8a2a28b7c31715a50c612

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - requests

test:
  imports:
    - pyrundeck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pschmitt/pyrundeck
  summary: Python REST API client for Rundeck 2.6+
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
