{% set name = "pyrundeck" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrundeck-{{ version }}.tar.gz
  sha256: 80b462ffb997cfdc9337e591622c4fa3a4fa7cf22ef4e0f8f4c8a8866fb58716

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - requests

test:
  imports:
    - pyrundeck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pschmitt/pyrundeck
  summary: Python REST API client for Rundeck 2.6+
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
